# Generated by Django 3.0.4 on 2020-03-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('sobrenome', models.CharField(max_length=50)),
                ('nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
    ]
